# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # Set Go environment variables
  GOPATH: "$CI_PROJECT_DIR/go"
  GOCACHE: "$CI_PROJECT_DIR/.cache/go-build"
  GOPRIVATE: "gitlab.arm.com"
  PACKAGE_NAME: "crismux"
  PACKAGE_VERSION: "1.0.0"

  
before_script:


stages:          # List of stages for jobs, and their order of execution
  - build
  - package
  - release
  

upload_package:
  stage: package
  dependencies:
    - build-crismux
  script:
  - |
    apk add curl
    curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $PACKAGE_NAME "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/$PACKAGE_NAME/$CI_COMMIT_TAG/$PACKAGE_NAME"
  only:
    - tags  # Only run this job when a tag is pushed
  except:
    - defaults  # Don't run this job when a default branch commit is pushed


build-crismux:
  stage: build
  image: golang:1.23.4
  script:
    - echo -e "machine gitlab.arm.com login gitlab-ci-token password ${CI_JOB_TOKEN}" > ~/.netrc
    - echo -e "machine git.gitlab.arm.com login gitlab-ci-token password ${CI_JOB_TOKEN}" >> ~/.netrc
    - go env -w GOPRIVATE="gitlab.com"
    - echo "Building crismux"
    - go build -o crismux
    - echo "Build finished"
  artifacts:
    paths:
      - 'crismux'
  only:
    - tags  # Only run this job when a tag is pushed
  except:
    - defaults  # Don't run this job when a default branch commit is pushed

release_job:
  stage: release
  dependencies:
    - upload_package
  image: gitlab/glab:latest
  only:
    - tags  # Only run this job when a tag is pushed
  except:
    - defaults  # Don't run this job when a default branch commit is pushed
  script:
    - glab auth login --hostname git.gitlab.arm.com --token ${MYTOKEN}
    - glab auth login --hostname gitlab.arm.com --token ${MYTOKEN}
    - glab release create "$CI_COMMIT_TAG" --ref main --assets-links "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/$PACKAGE_NAME/$CI_COMMIT_TAG/$PACKAGE_NAME"
